version: '3'
services:
  finaure-api:
    build: .
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: mongodb://mongo:27017/finaure
      JWT_SECRET: your_jwt_secret
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: